In [1]:
#question 1
import numpy as np
new_array=np.array([[3,4,5],[6,7,8]])

In [2]:
#question 2 
import numpy as np
a=np.array ([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
somme=np.trace(a)
somme 

15

In [4]:
#question 3
a=np.array ([[1,2],[3,5]])
a

array([[1, 2],
       [3, 5]])

In [5]:
x=2 
print (a[a>x])

[3 5]


In [6]:
#question 4
A=np.array ([[1,2,3],[4,5,6]])
B=np.array ([[7,8,9],[10,11,12]])

In [7]:
print (A)

[[1 2 3]
 [4 5 6]]


In [14]:
print (B)

[[ 7  8  9]
 [10 11 12]]


In [9]:
A.shape

(2, 3)

In [10]:
B.shape

(2, 3)

In [12]:
C=A+B
print (C)

[[ 8 10 12]
 [14 16 18]]


In [13]:
y=np.add(A,B)
y

array([[ 8, 10, 12],
       [14, 16, 18]])

In [15]:
#exercice 5
x=np.random.randint(10,20,size=(4,3))
x

array([[19, 13, 16],
       [18, 17, 16],
       [15, 12, 13],
       [14, 11, 10]])

In [18]:
f=x.shape
n=f[0]
n

4

In [19]:
for i in range (n):
    y=np.mean(x[i])
    print("the mean of row",i," =", y)

the mean of row 0  = 16.0
the mean of row 1  = 17.0
the mean of row 2  = 13.333333333333334
the mean of row 3  = 11.666666666666666
